services:
  - type: web
    name: wevolve-backend
    root: backend
    env: python
    region: singapore # You can change this (e.g., oregon, frankfurt)
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0